export const customers = [
  {
    id: 1,
    name: "John Doe",
    rfc: "DOEJ123456789",
    fiscalAddress: "Calle 123, Colonia Centro, CDMX",
    email: "client1@gmail.com",
    phone: "1234567890",
    contact: "Juan Perez",
    status: "active",
  },
  {
    id: 2,
    name: "Jane Smith",
    rfc: "SMIJ123456789",
    fiscalAddress: "Avenida 456, Colonia Norte, CDMX",
    email: "client2@gmail.com",
    phone: "0987654321",
    contact: "Ana Lopez",
    status: "active",
  },
  {
    id: 3,
    name: "Carlos Ruiz",
    rfc: "RUIC123456789",
    fiscalAddress: "Calle 789, Colonia Sur, CDMX",
    email: "client3@gmail.com",
    phone: "1122334455",
    contact: "Carlos Martinez",
    status: "active",
  },
  {
    id: 4,
    name: "Laura Gomez",
    rfc: "GOML123456789",
    fiscalAddress: "Avenida 101, Colonia Este, CDMX",
    email: "client4@gmail.com",
    phone: "5566778899",
    contact: "Laura Fernandez",
    status: "active",
  },
  {
    id: 5,
    name: "Miguel Torres",
    rfc: "TORM123456789",
    fiscalAddress: "Calle 202, Colonia Oeste, CDMX",
    email: "client5@gmail.com",
    phone: "6677889900",
    contact: "Miguel Sanchez",
    status: "active",
  },
];

export const shippingAddresses = [
  {
    id: 1,
    customerId: 1,
    NameShort: "Casa",
    address: "Calle 123, Colonia Centro, CDMX",
    postalCode: "12345",
    phone: "1234567890",
    contact: "Juan Perez",
    status: "active",
  },
  {
    id: 2,
    customerId: 1,
    NameShort: "Trabajo",
    address: "Avenida 456, Colonia Norte, CDMX",
    postalCode: "54321",
    phone: "0987654321",
    contact: "Ana Lopez",
    status: "active",
  },
  {
    id: 3,
    customerId: 2,
    NameShort: "Casa",
    address: "Calle 789, Colonia Sur, CDMX",
    postalCode: "67890",
    phone: "1122334455",
    contact: "Carlos Martinez",
    status: "active",
  },
  {
    id: 4,
    customerId: 2,
    NameShort: "Trabajo",
    address: "Avenida 101, Colonia Este, CDMX",
    postalCode: "09876",
    phone: "5566778899",
    contact: "Laura Fernandez",
    status: "active",
  },
  {
    id: 5,
    customerId: 3,
    NameShort: "Casa",
    address: "Calle 202, Colonia Oeste, CDMX",
    postalCode: "54321",
    phone: "6677889900",
    contact: "Miguel Sanchez",
    status: "active",
  },
  {
    id: 6,
    customerId: 4,
    NameShort: "Oficina",
    address: "Avenida 303, Colonia Norte, CDMX",
    postalCode: "65432",
    phone: "7788990011",
    contact: "Ana Lopez",
    status: "active",
  },
  {
    id: 7,
    customerId: 5,
    NameShort: "Bodega",
    address: "Calle 404, Colonia Sur, CDMX",
    postalCode: "76543",
    phone: "8899001122",
    contact: "Carlos Martinez",
    status: "active",
  },
  {
    id: 8,
    customerId: 3,
    NameShort: "Sucursal",
    address: "Avenida 505, Colonia Este, CDMX",
    postalCode: "87654",
    phone: "9900112233",
    contact: "Laura Fernandez",
    status: "active",
  },
];

export const products = [
  {
    id: 1,
    sku: "PROD1",
    description: "Producto 1",
    measurementUnit: "pieza",
    price: 100,
    status: "active",
  },
  {
    id: 2,
    sku: "PROD2",
    description: "Producto 2",
    measurementUnit: "litro",
    price: 200,
    status: "active",
  },
  {
    id: 3,
    sku: "PROD3",
    description: "Producto 3",
    measurementUnit: "kilogramo",
    price: 300,
    status: "active",
  },
  {
    id: 4,
    sku: "PROD4",
    description: "Producto 4",
    measurementUnit: "metro",
    price: 400,
    status: "active",
  },
  {
    id: 5,
    sku: "PROD5",
    description: "Producto 5",
    measurementUnit: "pieza",
    price: 500,
    status: "active",
  },
  {
    id: 6,
    sku: "PROD6",
    description: "Producto 6",
    measurementUnit: "litro",
    price: 600,
    status: "active",
  },
  {
    id: 7,
    sku: "PROD7",
    description: "Producto 7",
    measurementUnit: "kilogramo",
    price: 700,
    status: "active",
  },
  {
    id: 8,
    sku: "PROD8",
    description: "Producto 8",
    measurementUnit: "metro",
    price: 800,
    status: "active",
  },
  {
    id: 9,
    sku: "PROD9",
    description: "Producto 9",
    measurementUnit: "pieza",
    price: 900,
    status: "active",
  },
  {
    id: 10,
    sku: "PROD10",
    description: "Producto 10",
    measurementUnit: "litro",
    price: 1000,
    status: "active",
  },
];

export const orders = [
  {
    id: 1,
    idOrder: "ORD1",
    idCustomer: 1,
    idShippingAddress: 1,
    dateOrder: "2021-10-01",
    status: "active",
  },
  {
    id: 2,
    idOrder: "ORD2",
    idCustomer: 2,
    idShippingAddress: 2,
    dateOrder: "2021-10-02",
    status: "active",
  },
  {
    id: 3,
    idOrder: "ORD3",
    idCustomer: 3,
    idShippingAddress: 3,
    dateOrder: "2021-10-03",
    status: "active",
  },
  {
    id: 4,
    idOrder: "ORD4",
    idCustomer: 4,
    idShippingAddress: 4,
    dateOrder: "2021-10-04",
    status: "active",
  },
  {
    id: 5,
    idOrder: "ORD5",
    idCustomer: 5,
    idShippingAddress: 5,
    dateOrder: "2021-10-05",
    status: "active",
  },
];

export const productsOrders = [
  {
    id: 1,
    idOrder: "ORD1",
    idProduct: 1,
    quantity: 10,
    price: 100,
  },
  {
    id: 2,
    idOrder: "ORD1",
    idProduct: 2,
    quantity: 20,
    price: 200,
  },
  {
    id: 3,
    idOrder: "ORD1",
    idProduct: 3,
    quantity: 30,
    price: 300,
  },
  {
    id: 4,
    idOrder: "ORD1",
    idProduct: 4,
    quantity: 40,
    price: 400,
  },
  {
    id: 5,
    idOrder: "ORD2",
    idProduct: 5,
    quantity: 50,
    price: 500,
  },
  {
    id: 6,
    idOrder: "ORD2",
    idProduct: 6,
    quantity: 60,
    price: 600,
  },
  {
    id: 7,
    idOrder: "ORD3",
    idProduct: 7,
    quantity: 70,
    price: 700,
  },
  {
    id: 8,
    idOrder: "ORD3",
    idProduct: 8,
    quantity: 80,
    price: 800,
  },
  {
    id: 9,
    idOrder: "ORD3",
    idProduct: 9,
    quantity: 90,
    price: 900,
  },
  {
    id: 10,
    idOrder: "ORD4",
    idProduct: 10,
    quantity: 100,
    price: 1000,
  },
  {
    id: 11,
    idOrder: "ORD4",
    idProduct: 1,
    quantity: 110,
    price: 1100,
  },
  {
    id: 12,
    idOrder: "ORD4",
    idProduct: 2,
    quantity: 120,
    price: 1200,
  },
  {
    id: 13,
    idOrder: "ORD5",
    idProduct: 3,
    quantity: 130,
    price: 1300,
  },
  {
    id: 14,
    idOrder: "ORD5",
    idProduct: 4,
    quantity: 140,
    price: 1400,
  },
  {
    id: 15,
    idOrder: "ORD5",
    idProduct: 5,
    quantity: 150,
    price: 1500,
  },
];
